title: Get to know Aran Tang
author: Aran Tang
email: aran.tang916@gmail.com
description: > My name is Aran Tang. I enjoy consuming all forms of entertainment such as books, movies, TV shows, and especially video games. I love eating food from a variety of cultures from all around the world. As a hobby, I enjoy making digital art and have mostly been self-taught.  # this means to ignore newlines until "baseurl:"
  

# social links
twitter_username: Ta003Ar # DO NOT include the @ character, or else the build will fail!
github_username:  ArTa003 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
